[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin/*"
  to = "/admin-login.html"
  status = 302
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 302
  force = true
